version: "3"
services:
  web:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - dataBase
  dataBase:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
